### ISSUE TITLE
You'd better go to visit the Museum of Chinese Modern Literature.

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/npcr-subtitles#12]
https://github.com/rdrg109/npcr-subtitles/blob/04fb7007c2976dbc8f25b5ab583fad2d5e24cdac/sentences/43-2.yaml#L69C8-L69C75

**Comment by rdrg109** [comment]
从[这个网站](https://resources.allsetlearning.com/chinese/grammar/Expressing_"had_better"_with_"haishi")，我刚学到了“还是”有“had better”的意思。

done 2aad6e4
