### ISSUE TITLE
must be--is

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/npcr-subtitles#15]
https://github.com/rdrg109/npcr-subtitles/blob/04fb7007c2976dbc8f25b5ab583fad2d5e24cdac/sentences/43-2.yaml#L129

**Comment by rdrg109** [comment]
I agree with you that it should be "is", because he knows that Mr. Ba Jin is very old. I believe a better translation could be: "Mr. Ba Jin with such large age, ...". Do you agree with me?

```
- id: 414e68f072ed4720b8a16f382d6f2120
  zh-hans: 巴金先生这么大岁数了，
  pinyin: Bā Jīn xiānshēng zhème dà suìshule,
  en: Mr. Ba Jin with such large age,
  es:
- id: fe84c35339e74e25a349ebf4dc23c2c1
  zh-hans: 难道他会每天在那儿跟参观的人握手吗？
  pinyin: nándào tā huì měitiān zài nàr gēn cānguān de rén wòshǒu ma?
  en: is he really there everyday shaking hands with the visitors?
  es:
```

**Comment by rdrg109** [comment]
@fhxshrs Gracias por avisame que el contenido del texto del libro es diferente al contenido del vídeo. He incluido las dos versiones en el archivo `.yaml`. Ahora ¿podrías decirme si las traducciones en inglés te parecen correctas?

**Comment by fhxshrs** [comment]
Me parecen correctas

**Comment by rdrg109** [comment]
> Me parecen correctas

Entonces cierro este issue.
