### ISSUE TITLE
中国现代文学馆Museum of Chinese Modern Literature

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/npcr-subtitles#23]
https://github.com/rdrg109/npcr-subtitles/blob/5a313a40b1476bf8f7ffddf5acdd9e4e1069a29e/sentences/43-2.yaml#L69

**Comment by rdrg109** [comment]
¿Por qué cerraste este issue? 

Creo que la traducción debería ser "Museum of Modern Chinese Literature". Ya hice los cambios en cccb15664a67d9299200b14a9a5ef556d91cb8c2 . Si no estás de acuerdo conmigo, hazmelo saber.

**Comment by fhxshrs** [comment]
我刚才查了维基百科，这个专有名词的翻译应该是National Museum of Modern Chinese Literature

**Comment by rdrg109** [comment]
@fhxshrs ¡Gracias por la información! Ya lo añadí: 79ac659

He puesto la palabra "National" entre paréntesis, porque no está expresada explícitamente.

**Comment by fhxshrs** [comment]
好的
