### ISSUE TITLE
很遗憾。--去掉后引号

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/npcr-subtitles#25]
https://github.com/rdrg109/npcr-subtitles/blob/5a313a40b1476bf8f7ffddf5acdd9e4e1069a29e/sentences/43-2.yaml#L102

这是书上对于引号的处理。虽然我也觉得很奇怪，后面这段话照理来说应该还是力波的话，但是不知道为什么课本上这样处理，不知道是不是版本的问题。你的书上是怎么写的？

**Comment by rdrg109** [comment]
Yo también creo que es un problema de edición. Esto es lo que muestra mi libro:

![image](https://github.com/rdrg109/npcr-subtitles/assets/74389646/53a5d107-a4ad-4ae3-95b0-81fb124570ab)

Ahora la pregunta es ¿Deberíamos mostrar el mismo contenido del libro o corregir el error del libro? @fhxshrs  ¿Qué crees que es lo mejor?

**Comment by fhxshrs** [comment]
我觉得按正确的来吧，上课的时候我会跟学生指出来。

**Comment by rdrg109** [comment]
done 0c1ed67
