### ISSUE TITLE
这一句也应该删除

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/npcr-subtitles#27]
https://github.com/rdrg109/npcr-subtitles/blob/5a313a40b1476bf8f7ffddf5acdd9e4e1069a29e/sentences/43-2.yaml#L137

**Comment by rdrg109** [comment]
@fhxshrs  Las oraciones que están en los archivos `*.yaml` contienen las oraciones que aparecen en el libro y en el texto. Hacemos esto porque vamos a generar 2 tipos de vídeos con subtítulos: (1) para los vídeos y (2) para los audios de los textos. Entonces, las oraciones que aparecen en el vídeo, pero no en el libro, no deben ser eliminadas. Acá hay dos ejemplos de los dos tipos de vídeos:

(1)

https://github.com/rdrg109/npcr-subtitles/assets/74389646/3e1fba2d-a025-44e1-b2b5-d4d0abe530cc

(2)

https://github.com/rdrg109/npcr-subtitles/assets/74389646/a282e915-544a-4e81-85cb-b9337b1f1aef

**Comment by fhxshrs** [comment]
Entendido
