### ISSUE TITLE
课文里这一处应该是“大家都觉得很奇怪”

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/npcr-subtitles#29]
https://github.com/rdrg109/npcr-subtitles/blob/5a313a40b1476bf8f7ffddf5acdd9e4e1069a29e/sentences/43-2.yaml#L267

**Comment by rdrg109** [comment]
Listo! 459befc

No he editado la oración, sino he añadido la oración del libro. Ahora tenemos dos oraciones (la que aparece en el libro y la que aparece en el vídeo). Una de las oraciones será mostrada en el vídeo, la otra oración será mostrada en el audio del libro.

Aún no te he mostrado como se ve un vídeo hecho para el audio del libro, te lo mostraré luego.
