### ISSUE TITLE
"I felt very strange" vs "I thought this was very strange"

### ISSUE THREAD

**Issue by rdrg109** [rdrg109/npcr-subtitles#31]
@fhxshrs Which translation do you think is more accurate?

(1) "I felt very strange."
(2) "I thought this was very strange."

https://github.com/rdrg109/npcr-subtitles/blob/003541e8c551312aabf15a715c758ae5f771086d/sentences/43-2.yaml#L111-L114

**Comment by fhxshrs** [comment]
我觉得（2）吧，因为是马大为对丁力波说的话感到很奇怪。

**Comment by rdrg109** [comment]
Ok, no cambiaré esa oración, pero he cambiado una oración que es similar. Mirar ab46c8d

Cierro este issue.
