### ISSUE TITLE
it was translated into English

### ISSUE THREAD

**Issue by fhxshrs** [rdrg109/npcr-subtitles#8]
https://github.com/rdrg109/npcr-subtitles/blob/04fb7007c2976dbc8f25b5ab583fad2d5e24cdac/sentences/43-2.yaml#L34

**Comment by rdrg109** [comment]
https://github.com/rdrg109/npcr-subtitles/blob/bd65df5715c3f462135f85294c8e3ecb03ed0162/sentences/43-2.yaml#L26-L35

I think there are two possible scenarios here: 

1. 马大为 expresses that he read the novel in Chinese, and he wants to let people know that there's an English translation of that book. Under this assumption, the translation is: **I read Ba Jin’s novel “The Family”, the novel has been translated into English.**

3. 马大为 expresses that he read that novel, and the version that he read was English translation of the original version (which we know was written in Chinese).  Under this assumption, the translation is: **I read Ba Jin’s novel “The Family”, it was an English translation.**

@fhxshrs Which do you think is the correct scenario?

**Comment by fhxshrs** [comment]
现在我更倾向于2了。

**Comment by rdrg109** [comment]
> 现在我更倾向于2了。

Then, I'm closing this issue because there's no need to change anything.
